coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment: false
