[package]
name = "git-releaser"
version = "0.2.1-0"
authors = ["Egill Sveinbjörnsson <egillsveinbjorns@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
semver = "1.0.1"
chrono = "0.4.19"
eyre = "0.6.5"
log = "0.4.14"
env_logger = "0.8.3"
dialoguer = "0.8.0"
hubcaps = "0.6.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.64"
features = ["preserve_order"]

[dependencies.toml]
version = "0.5.8"
features = ["preserve_order"]

[dependencies.tokio]
version = "0.2.25"
features = ["rt-threaded", "macros"]
