[package]
name = "git-releaser"
version = "0.2.1-0"
authors = ["Egill Sveinbjörnsson <egillsveinbjorns@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.0.6", features = ["derive"] }
semver = "1.0.4"
chrono = "0.4.19"
eyre = "0.6.5"
log = "0.4.14"
env_logger = "0.9.0"
dialoguer = "0.9.0"
hubcaps = "0.6.2"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = { version = "1.0.74", features = ["preserve_order"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
tokio = { version = "1.15.0", features = ["full"] }
