[package]
name = "git-releaser"
version = "0.1.1-0"
authors = ["Egill Sveinbjörnsson <egillsveinbjorns@gmail.com>"]
edition = "2018"

[dependencies]
semver = "0.11.0"
chrono = "0.4.19"
eyre = "0.6.3"
log = "0.4.11"
env_logger = "0.8.2"
dialoguer = "0.7.1"
hubcaps = "0.6.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.60"
features = ["preserve_order"]

[dependencies.toml]
version = "0.5.7"
features = ["preserve_order"]

[dependencies.structopt]
version = "0.3"
default-features = false

[dependencies.tokio]
version = "0.2.24"
features = ["rt-threaded", "macros"]
