[package]
name = "git-releaser"
version = "0.1.0"
authors = ["Egill Sveinbjörnsson <egillsveinbjorns@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.114"
serde_json = { version = "1.0.56", features = ["preserve_order"] }
semver = "0.10.0"
structopt = { version = "0.3", default-features = false }
